spring:
    datasource:
        password: 
        url: jdbc:h2:mem:testdb
        username: sa
        driver-class-name: org.h2.Driver
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
